version: '20.10.17'
services:
  web:
    build: .
    command: python /currency_yahoo_rest_api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/currency_yahoo_rest_api
    ports:
      - 8000:8000 