# Generated by Django 3.2.15 on 2022-09-26 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('symbol', models.CharField(max_length=3, unique=True, verbose_name='Symbol')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_cost', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Open cost')),
                ('high_cost', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='High cost')),
                ('low_cost', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Low cost')),
                ('close_cost', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Close cost')),
                ('adj_close_cost', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Adjusted close cost')),
                ('currency1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exchange_currency1', to='currency.currency', verbose_name='Currency 1')),
                ('currency2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exchange_currency2', to='currency.currency', verbose_name='Currency 2')),
            ],
            options={
                'verbose_name': 'ExchangeRate',
                'verbose_name_plural': 'ExchangeRates',
                'ordering': ['currency1'],
            },
        ),
    ]
