# Generated by Django 3.2.15 on 2022-09-26 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_exchangerate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=3, unique=True, verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 13, 27, 1, 343289), verbose_name='Date'),
        ),
    ]
