# Generated by Django 3.2.15 on 2022-09-26 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20220926_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=3, verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 13, 31, 17, 933551), verbose_name='Date'),
        ),
    ]
